### ISSUE TITLE
Avogadro does not open .xyz by clicking

### ISSUE THREAD

**Issue by imitrichev** [OpenChemistry/avogadrolibs#1649] opened 2024-03-07 19:56 UTC
**Avogadro version: 1.99.0 (installed using installer)
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Describe the bug**
Avogadro does not open .xyz files (fails to launch) when double clicking on them. Also when - Open with - Avagadro 2.
Avogadro 2 is registered as app to open for .xyz system-wide.
Also, if I fed .xyz directly to avogadro.exe (Explorer shows - Open in), is does not work.
If I open an empty Avogadro and then open .xyz file through File -> Open - it works.

**To Reproduce**
1. Go to any folder with .xyz file
2. Double click on .xyz
3. Avogadro does not appear on the screen. In Task Manager Avoagadro2 appears and disappears very soon.

**Expected behavior**
File is opened in Avogadro

**Additional context**
There were Avogadro 1.98 and 1.2 on my computer when I installed 1.99, and problem appeared only with 1.99. When deleteing any version and then reinstalling 1.99, problem persists.

**Comment by ghutchis** [comment] 2024-03-07 20:40
It sounds like the problem isn't so much that Avogadro 1.99 doesn't open an XYZ file as it crashing on startup no matter what. Correct?

We have fixed a variety of bugs and crashes, can you try a nightly build?
https://two.avogadro.cc/

**Comment by imitrichev** [comment] 2024-03-11 21:30
Thanks, will try in a couple of days and answer!

**Comment by ghutchis** [comment] 2024-11-14 20:35
Have you been able to try a nightly build? As far as I can tell, these issues are resolved, but I'd like to know before we release the next version.

**Comment by ghutchis** [comment] 2024-11-30 17:59
Okay, I'm closing this - if you're having problems with one of the nightly builds, please open a new bug.

**Closed by ghutchis** 2024-11-30 17:59 UTC
