### ISSUE TITLE
Bad Geometry

### ISSUE THREAD

**Issue by Jtyndallnz** [OpenChemistry/avogadrolibs#1217] opened 2023-02-01 01:32 UTC
**Avogadro version: 1.97.0):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows
 - Version 10
 - Compiler (if you built from source) NA

**Describe the bug**
When trying to minimise (Extensions > Open Babel > optimise geom) an aromatic azide it doesnt. It should have a C.ar-N=N angle of ~120 but is about 180 ish.

**To Reproduce**

**Expected behavior**
See above

**Screenshots**
![image](https://user-images.githubusercontent.com/124109377/215922836-f4680095-c704-42ca-84a0-ec53d9580b01.png)

**Additional context**
AAdditional heterocyclic nitrogen should be planar also. Avogadro 1.2.0 Q4.8.6 does not have this problem

**Comment by ghutchis** [comment] 2023-03-10 18:54
Can you upload the CJSON file? I can't currently reproduce this, thanks.

**Comment by Jtyndallnz** [comment] 2023-03-14 21:20
Try this

**Comment by ghutchis** [comment] 2023-03-14 22:05
I don't think you can upload files to GitHub via email, unfortunately.

Can you gzip or ZIP the file and upload on the issue page? Thanks!

**Comment by Jtyndallnz** [comment] 2023-03-14 22:31
Sorry, didn't see the "upload"

**Comment by Jtyndallnz** [comment] 2023-03-14 22:40
[azide.zip](https://github.com/OpenChemistry/avogadrolibs/files/10974469/azide.zip)

**Comment by ghutchis** [comment] 2023-05-10 13:32
I can't reproduce this on my Mac. Can you try a recent nightly build:
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

<img width="563" alt="Screenshot 2023-05-10 at 3 32 12 PM" src="https://github.com/OpenChemistry/avogadrolibs/assets/41128/b4414a24-8279-4c94-b7a7-49c4bfa6897e">

**Comment by ghutchis** [comment] 2023-09-10 20:38
I'm closing this - as far as I can tell, it's fixed in the current development code.

**Closed by ghutchis** 2023-09-10 20:38 UTC
Labels: bug
