### ISSUE TITLE
Cannot delete all selected atoms

### ISSUE THREAD

**Issue by mquevill** [OpenChemistry/avogadrolibs#654] opened 2021-07-07 16:09 UTC
**Avogadro version: 1.94.0-17-gb2b873b**
 - Avogadrolibs: 1.94.0-76-g5c867a2
 - Qt: 5.12.8

**Desktop version:**
 - OS & Version: Linux Mint 20.1 (based on Ubuntu 20.04)
 - Compiler: gcc 9.3.0

**Describe the bug**
When multiple atoms are selected, pressing "delete" (on keyboard) does not delete all selected atoms. The remaining atoms are still selected, but it can take several steps to actually delete all of the originlly selected atoms.

**To Reproduce**
Select multiple atoms and tap "delete". Only some atoms are actually deleted.

**Expected behavior**
All selected atoms would be deleted.

**Screenshots**
Creating CH4 with the draw tool and adjust hydrogens turned on:
![image](https://user-images.githubusercontent.com/17033543/124792563-18e98400-df1b-11eb-9db6-fc0b34256668.png)
Selected all atoms:
![image](https://user-images.githubusercontent.com/17033543/124792655-2f8fdb00-df1b-11eb-9adc-110a0e7a10fa.png)
After pressing "delete":
![image](https://user-images.githubusercontent.com/17033543/124792691-3b7b9d00-df1b-11eb-9316-72597efeb96f.png)
After pressing "delete" again:
![image](https://user-images.githubusercontent.com/17033543/124792736-46cec880-df1b-11eb-9ab0-2c60031519ac.png)
Pressing "delete" again cleared the last atom. I needed to press "delete" 3 times to fully remove this simple molecule.

**Additional context**
It seems like it is usually hydrogens that are left after trying to delete all the atoms. With H2, it takes 2 presses to delete all atoms. However, with a molecule like CO2, pressing "delete" only removes one of the O atoms.

**Comment by mquevill** [comment] 2021-07-07 18:46
Possibly related to #650.

[Sorry for posting in the wrong repo, I'll make sure to post in the right repo next time!]

**Comment by ghutchis** [comment] 2021-07-08 18:06
This is a duplicate of #650 - clearly the delete and selection aren't updated properly. I'm going to close this and add you to the other issue.

**Closed by ghutchis** 2021-07-08 18:06 UTC
