### ISSUE TITLE
export molecule fails silently: returns back to save dialog

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#439] opened 2020-02-10 03:55 UTC
**Avogadro version: 1.93.0**
 - Avogadrolibs: 1.93.0 (debian 1.93.0-1)
 - Qt: 5.12.5

**Desktop version: (please complete the following information):**
 - OS: Linux (Debian)
 - Version Linux 5.4.13 on debian unstable
 - Compiler: g++ 9.2.1

**Describe the bug**

The Export to Molecule functionality is failing (trying to save to file, e.g. to .cml, or .tmol or .xyz).
The save dialog box pops up, but when a file and format is selected, the save dialog box pops up again instead of generating the molecular coordinate file.

There is some instability in the Export to Molecule functionality (obviously).  The bug is reproducible every time, but in the middle of attempting to export, it sometimes does write a file anyway (while still popping back to the Save dialog).  These "successful" writes are not reproducible, i.e. export is only randomly successful.

**To Reproduce**
1. Create a molecule (e.g. click on initial screen to create methane)
2. Go to File->Export->Molecule in the menu
3. When save dialog comes up, type "methane.cml" (or any other relevant suffix)
4. Dialog box pops up to ask "Multiple writers found that can write this format. Which should be used?"
Select "Avogadro: CML".  (or select "OpenBabel: Chemical Markup Language", the failure is the same)
5. The Save dialog pops up again with no error message, and the coordinate file has not been written.

**Expected behavior**
After step 4, a coordinate file (methane.cml) should have been written, and the save dialog box should not reappear.

**Comment by RizzerOnGitHub** [comment] 2020-02-10 04:00
I suspect the problem might be related to how the obabel process is spawned to generate the files.

**Comment by RizzerOnGitHub** [comment] 2020-02-10 05:59
I can see some pattern in the successful write: write seems to proceeds if I cancel the second Save dialog box (e.g. press the  Esc button).  So the problem is, why is it returning back to that Save dialog?  Perhaps it is a bug in avogadroapp rather than avogadrolib?

**Comment by cryos** [comment] 2020-02-10 14:47
I can reproduce, we moved to latest Open Babel and this may be one I missed. I will see what I can do to get this fixed up. Thanks for reporting, and for the great description.

**Comment by anubh4v** [comment] 2021-01-26 11:14
There is another thing I noticed. When save dialog pops up again, if you click on cancel the file gets saved successfully.
![ezgif com-video-to-gif1](https://user-images.githubusercontent.com/52047994/105838132-aed8c480-5ff5-11eb-9300-4eb82a675b81.gif)

**Comment by Krzmbrzl** [comment] 2021-03-03 16:30
I also encountered this in v1.93 (Ubuntu 20.04)

Cancelling the second save dialog seems to reliably cause the file to actually get saved.

**Comment by ghutchis** [comment] 2021-04-14 18:36
IIRC, this is fixed ,thanks to @anubh4v - I'm closing this.

**Closed by ghutchis** 2021-04-14 18:36 UTC
Labels: bug
