### ISSUE TITLE
Edit > Graphics doesn't do anything

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1203] opened 2022-12-04 22:04 UTC
**Avogadro version: (please complete the following information from the About box):**
- Flatpak of version 1.97.0 
- Avogadrolibs: 1.97.0
 - Qt: 5.15.7

**Desktop version: (please complete the following information):**
 - OS: Linux OpenSUSE Tumbleweed
 - Version 20221201
 - Also same behaviour on Windows 10

**Describe the bug**
Choosing "Graphics" from the Edit menu does nothing on my version of Avogadro, regardless of whether a molecule is currently being displayed or not. This is the same both on the Linux flatpak version or in the Windows exe.

**To Reproduce**
1. Go to 'Edit'
2. Click on 'Graphics'
3. See error (nothing happens)

**Expected behavior**
I don't know but presumably the button is meant to do something since it is there...

**Comment by ghutchis** [comment] 2022-12-05 00:08
What language / localization are you using? There's File => Export => Graphics and Edit => Copy Graphics, but I suspect the problem is an issue with the language pack.

**Comment by ghutchis** [comment] 2022-12-05 00:09
You can test this by switching to American English (en_US)

**Comment by matterhorn103** [comment] 2022-12-05 22:41
Yes you seem to be right, Edit > Graphics on my version seems to be what should be called Edit > Copy Graphics, and indeed clicking on it does copy the viewing pane to the clipboard.

This is all using the system language as the UI language, which in my case is British English. Weirdly, I don't have the option for American English in the languages list. Australian and Canadian English seem to say the same as BE. German has a more sensible name for it though.

**Comment by ghutchis** [comment] 2023-04-16 02:40
This is also fixed now, thanks.

**Closed by ghutchis** 2023-04-16 02:40 UTC
