### ISSUE TITLE
Enabling input generation requires manual intervention

### ISSUE THREAD

**Issue by antoscha** [OpenChemistry/avogadrolibs#416] opened 2018-12-14 13:58 UTC
Plugin downloader extracts `avogenerators.zip` into `$HOME/.local/share/OpenChemistry/Avogadro/other` for some reason, while they are expected to be in `$HOME/.local/share/OpenChemistry/Avogadro/inputGenerators`

**Comment by ghutchis** [comment] 2018-12-14 17:10
The problem is partly on the downloader side and partly on the server side. 
- We’re working to spin up a real plugin repository
- The downloader will be fixed
- We’re also adding a command to install a script manually (i.e., outside of the downloader).

**Closed** 2021-05-28 21:30 UTC
Labels: bug
