### ISSUE TITLE
Optimize Geometry - Error interpreting Open Babel Output

### ISSUE THREAD

**Issue by frda058** [OpenChemistry/avogadrolibs#482] opened 2020-07-07 19:57 UTC
**Avogadro version: 1.93.0**
 - Avogadrolibs: 1.93.0
 - Qt: 5.12.8
- Downloaded from https://github.com/OpenChemistry/avogadrolibs/suites/648275435/artifacts/5525298

**Desktop version:**
 - OS: macOS Catalina
 - Version 10.15.5

Issue:
When I click Extensions > Open Babel > Optimize Geometry, I get the following error message:
<img width="372" alt="Screen Shot 2020-07-07 at 3 52 42 PM" src="https://user-images.githubusercontent.com/67458938/86835405-0cadbb00-c06a-11ea-99f0-3e86ba2c8cef.png">

I downloaded Open Babel 2.4.1 using the instructions on http://openbabel.org/docs/dev/Installation/install.html

<img width="749" alt="Screen Shot 2020-07-09 at 2 54 07 PM" src="https://user-images.githubusercontent.com/67458938/87079463-1bc07480-c1f4-11ea-959e-c95fc7189a0b.png">

When I type " obabel -L formats ", I am able to see the list of formats, so I do have open babel downloaded. I'm not sure if the problem is that the location of open babel can't be found.

Please advise on how to address the issue. I am not sure if there are any other components that need to be downloaded to use the Optimize Geometry functionality. Thanks!

**Comment by ghutchis** [comment] 2020-07-09 19:15
@frda058 - was your problem resolved?

**Comment by ghutchis** [comment] 2020-07-09 19:16
You don't need to download Open Babel separately. The key question is - what molecule / system are you trying to optimize?

**Comment by frda058** [comment] 2020-07-09 19:30
The optimize option was not working for me for even the basic molecules I was creating (ex. propane).

I was able to somehow fix the problem by going to Avogadro2's package contents and replacing the obabel Unix executable file in the MacOS folder and the .so files in the  lib>openbabel folder with same files found from the build installation. I'm not sure if this is the "right" fix, but it seemed to work for me. I only happened to stumble upon this by trial and error.

**Comment by ghutchis** [comment] 2020-07-11 23:28
Let me understand - the build wasn't working, and the `obabel` and `.so` files were in a different place?

Or are you saying that you replaced those from a different install? If so, what was the broken build and what was the "fixed" build?

All the builds should work, so  I'd like to get to the bottom of this, particularly since I want to release a 1.94 version soon. Thanks!

**Comment by frda058** [comment] 2020-07-12 00:51
I replaced those from a different install. I replaced the obabel and .so files from the Avogadro 1.93.0 version with the corresponding files from the Open Babel version 2.4.1 from https://sourceforge.net/projects/openbabel/files/latest/download . I followed the basic build procedure for Open Babel from my previous post. Thanks for being on top of this!

**Comment by ghutchis** [comment] 2021-05-28 21:28
I'm going to close this - I'm confident that the current builds (and 1.94 release) work on my Mac and others.
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master

Obviously, if you run into problems again, please re-open or submit a new issue. Thanks!

**Comment by rwexler** [comment] 2021-06-22 14:03
I'm running into the exact same issue with the 1.94 release. In this case, I'm trying to optimize a methane molecule. I'm running on macOS Catalina version 10.15.3. I'm not sure if it's the cause of these issues but I noticed that Open Babel version 2.4.1 is already installed on my machine (possible via conda at https://anaconda.org/openbabel/openbabel). Thanks in advance for your help!

**Comment by ghutchis** [comment] 2021-06-22 15:04
Yeah, that's really weird. It's not loading any of the formats, so you won't be able to do any of that.
`Open Babel formats ready:  0`

I'd really like to figure out why this is happening. Can you run a few things for me?
`/Applications/Avogadro2.app/Contents/MacOS/obabel -L formats`

If you have Xcode / developer tools installed, I'd love to see:
`otool -L /Applications/Avogadro2.app/Contents/MacOS/obabel`

**Comment by rwexler** [comment] 2021-06-22 15:29
For the first command, I get:

`==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
formats is not a recognized plugin type. Those with instances of sub-types loaded are:
ops`

For the second command, I get:

`/Applications/Avogadro2.app/Contents/MacOS/obabel:
	@executable_path/../Frameworks/libopenbabel.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	@executable_path/../Frameworks/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)`

**Comment by ghutchis** [comment] 2021-06-22 15:48
That explains a lot. Let me poke around and figure out why the BABEL_LIBDIR isn't getting set properly.

**Comment by ghutchis** [comment] 2021-06-22 16:03
Let's try something else...
`ls /Applications/Avogadro2.app/Contents/lib/openbabel/`

Run:
`export BABEL_LIBDIR=/Applications/Avogadro2.app/Contents/lib/openbabel/; /Applications/Avogadro2.app/Contents/MacOS/obabel -L formats`

**Comment by ghutchis** [comment] 2021-06-22 16:04
(I downloaded the build and I'm poking around - I think I see the problem...)

**Comment by rwexler** [comment] 2021-06-22 16:08
For the first command, I get:

```
APIInterface.so		asciiformat.so		chemdrawct.so		daltonformat.so		freefracformat.so	jaguarformat.so		mpdformat.so		pdbqtformat.so		pubchem.so		svgformat.so		xsfformat.so
CSRformat.so		balstformat.so		chemkinformat.so	dlpolyformat.so		gamessformat.so		lmpdatformat.so		mpqcformat.so		plugin_charges.so	pwscfformat.so		textformat.so		xyzformat.so
MCDLformat.so		bgfformat.so		chemtoolformat.so	dmolformat.so		gamessukformat.so	lpmdformat.so		msiformat.so		plugin_descriptors.so	qchemformat.so		thermoformat.so		yasaraformat.so
MNAformat.so		boxformat.so		cifformat.so		exyzformat.so		gausscubeformat.so	mdffformat.so		msmsformat.so		plugin_fingerprints.so	reportformat.so		tinkerformat.so		zindoformat.so
PQSformat.so		cacaoformat.so		cmlformat.so		fastaformat.so		gaussformat.so		mdlformat.so		nulformat.so		plugin_forcefields.so	rinchiformat.so		titleformat.so
abinitformat.so		cacheformat.so		cmlreactformat.so	fastsearchformat.so	gausszmatformat.so	mmcifformat.so		nwchemformat.so		plugin_ops.so		rsmiformat.so		turbomoleformat.so
acesformat.so		carformat.so		cofformat.so		fchkformat.so		ghemicalformat.so	mmodformat.so		opendxformat.so		png2format.so		rxnformat.so		unichemformat.so
acrformat.so		castepformat.so		confabreport.so		featformat.so		groformat.so		mol2format.so		orcaformat.so		pngformat.so		shelxformat.so		vaspformat.so
adfformat.so		cccformat.so		copyformat.so		fhformat.so		gromos96format.so	moldenformat.so		outformat.so		pointcloudformat.so	siestaformat.so		viewmolformat.so
alchemyformat.so	cdxmlformat.so		crkformat.so		fhiaimsformat.so	gulpformat.so		molproformat.so		painterformat.so	posformat.so		smilesformat.so		wlnformat.so
amberformat.so		chem3dformat.so		crystal09format.so	fingerprintformat.so	hinformat.so		molreport.so		pcmodelformat.so	povrayformat.so		smileyformat.so		xedformat.so
aoforceformat.so	chemdrawcdx.so		cssrformat.so		fpsformat.so		inchiformat.so		mopacformat.so		pdbformat.so		pqrformat.so		stlformat.so		xmlformat.so
```

For the second command, I get a long list of loading errors with the last two being:

```
==============================
*** Open Babel Error  in openLib
  /Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so did not load properly.
 Error: dlopen(/Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so, 9): Library not loaded: /usr/local/opt/cairo/lib/libcairo.2.dylib
  Referenced from: /Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so
  Reason: image not found
==============================
*** Open Babel Error  in LoadAllPlugins
  No valid OpenBabel plugs found in /Users/runner/work/avogadrolibs/build/prefix/lib/openbabel
```

Let me know if you need me to send you the whole log.

By the way, thanks for your lightning fast responses on this!

–Rob

**Comment by ghutchis** [comment] 2021-06-22 16:12
Yeah, working on that. Evidently the GitHub build servers include a bunch of things…

**Comment by ghutchis** [comment] 2021-06-23 02:34
Let me know if this build works better:
https://github.com/OpenChemistry/avogadrolibs/suites/3061586250/artifacts/69693080

**Comment by rwexler** [comment] 2021-06-23 02:42
Unfortunately, this too did not work. Got the same `Open Babel formats ready:  0` issue. Attached the anonymized log but I don't think there are any differences from the previous one I sent.

[new-build-log.txt](https://github.com/OpenChemistry/avogadrolibs/files/6698538/new-build-log.txt)

**Comment by ghutchis** [comment] 2021-06-23 03:27
Can you try running this again?
```
export BABEL_LIBDIR=/Applications/Avogadro2.app/Contents/lib/openbabel/; /Applications/Avogadro2.app/Contents/MacOS/obabel -L formats
```

Thanks...

**Comment by rwexler** [comment] 2021-06-23 04:00
Sure, I get a long list of loading errors like the following:

```
==============================
*** Open Babel Error  in openLib
  /Applications/Avogadro2.app/Contents/lib/openbabel//ghemicalformat.so did not load properly.
 Error: dlopen(/Applications/Avogadro2.app/Contents/lib/openbabel//ghemicalformat.so, 9): Library not loaded: @executable_path/../Frameworks/libinchi.0.dylib
  Referenced from: /Applications/Avogadro2.app/Contents/lib/openbabel//ghemicalformat.so
  Reason: image not found
==============================
*** Open Babel Error  in openLib
  /Applications/Avogadro2.app/Contents/lib/openbabel//gausszmatformat.so did not load properly.
 Error: dlopen(/Applications/Avogadro2.app/Contents/lib/openbabel//gausszmatformat.so, 9): Library not loaded: @executable_path/../Frameworks/libinchi.0.dylib
  Referenced from: /Applications/Avogadro2.app/Contents/lib/openbabel//gausszmatformat.so
  Reason: image not found
==============================
*** Open Babel Error  in openLib
  /Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so did not load properly.
 Error: dlopen(/Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so, 9): Library not loaded: @executable_path/../Frameworks/libinchi.0.dylib
  Referenced from: /Applications/Avogadro2.app/Contents/lib/openbabel//dlpolyformat.so
  Reason: image not found
formats is not a recognized plugin type. Those with instances of sub-types loaded are:
charges
descriptors
fingerprints
forcefields
loaders
ops
```

**Comment by ghutchis** [comment] 2021-06-23 04:22
Thanks - and thanks for your patience! Closer to a fix at least. Here's another pull request that should help.
https://github.com/OpenChemistry/avogadrolibs/pull/628

**Comment by ghutchis** [comment] 2021-06-23 17:38
@rwexler - can you give this a try? I think it'll work. If not, the `export BABEL_LIBDIR` bit above would help figure out what else is wrong.

Thanks for your help - I think we can get this fixed soon.

**Comment by rwexler** [comment] 2021-06-23 17:45
@ghutchis – it worked! Well done! What was the issue might I ask?

**Comment by ghutchis** [comment] 2021-06-23 18:45
There were two issues:
- It was linking to `libcairo` on the GitHub build systems, which Open Babel uses for PNG depiction, but isn't very useful in the scheme of Avogadro
- The `libinchi` which is used by Open Babel wasn't bundled in the app. MacOS is good about finding missing libraries, so it works on my computers.. but not if you don't have `libinchi` on your system.

Thanks for the help in tracking this one down!

**Closed by ghutchis** 2021-06-23 18:45 UTC
Labels: bug

**Comment by rwexler** [comment] 2021-06-24 02:59
Thanks, @ghutchis, happy to help!
