### ISSUE TITLE
spacegroupdata.h has two identical entries and two invalid caracters

### ISSUE THREAD

**Issue by bonfus** [OpenChemistry/avogadrolibs#153] opened 2016-12-30 15:20 UTC
I was trying to (re)use the nice spacegroup data of this project in another code when I noticed that:

- there are two illegal '#' characters in the symmetry operation entries of space_group_transforms
- the symmetry operations of hall numbers 506 and 515 are identical. I suspect that 506 is wrong.
- I also suspect that there is a mistake in the entry 450 (see [bilbao](http://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-trgen?gnum=160&what=gp&trmat=2/3a+1/3b+1/3c,-1/3a+1/3b+1/3c,-1/3a-2/3b+1/3c&unconv=R%203%20m%20:R&from=ita) )

Hope this helps,
best wishes for the new year,
Pietro

**Comment by ghutchis** [comment] 2016-12-31 21:40
We have been using spglib but we'll definitely check these, thanks.

@psavery - do you have any comments?

**Comment by psavery** [comment] 2017-01-06 20:32
It looks like he is probably right. Please note that I got this data from OpenBabel (https://github.com/openbabel/openbabel/blob/master/data/space-groups.txt), so anything that is wrong here is also wrong there (I can confirm that the illegal '#' characters are also in OpenBabel).

I will try to fix this soon. I'm probably going to have to write some parsers to aid me (I'm not sure if it matters for the parsers that Bilbao does things like "x+1/2" instead of OpenBabel doing "1/2+x", but I should probably get it to do that just in case).

**Comment by ghutchis** [comment] 2017-12-27 20:29
@psavery - I'm going through old issues. It seems like Open Babel has updated space-groups.txt that everyone is "happy" with? (At least it hasn't been changed in a few months.)

Can we fix this one?

**Comment by psavery** [comment] 2017-12-27 21:36
Okay. I need to re-write the script that will parse the space groups file in Open Babel and generate this file from it. I'll try to do that soon.

**Comment by psavery** [comment] 2018-01-02 20:57
Alright. I think this issue should be fixed now.

**Comment by ghutchis** [comment] 2018-03-15 00:03
Thanks @psavery

**Closed** 2018-03-15 00:03 UTC
